### ISSUE TITLE
Format only staged parts

### ISSUE THREAD

**Issue by mgudemann** [hallettj/git-format-staged#2]
Hi, thanks for this project this is really nice.

It seems that when I have a file that contains unchanged lines (U), changed but unstaged lines (C) and staged lines (A), then `git-format-staged` applies the formatting to U and A, but ignores C, right? (at least this is how `hfmt` did it for me when using it with Haskell)

My use case is that I would like it to be applied to A only. Is that possible?

**Comment by hallettj** [comment]
Hi Matthias, thanks for the suggestion! I can see the use case; but it
would be a big change to ignore unchanged lines, and I don't want to
implement that myself. Currently the tool runs a formatter on the entirety
of the staged copy of a file. Formatting only A lines would require either
support for partial-file formatting from the formatter, or selectively
reverting formatting changes to U lines.

**Comment by mgudemann** [comment]
Hi Jessie,
I proposed an approach to do this in #3. It would be great to get your feedback. Would you be interested to merge such a feature?

**Comment by hallettj** [comment]
Since we have not come up with a solution yet I'm closing this issue.
