### ISSUE TITLE
Use working tree files when they are fully staged

### ISSUE THREAD

**Issue by ccope** [hallettj/git-format-staged#5]
This would avoid forking lots of extra processes in the case where files are fully staged, which could be a bottleneck when dealing with large numbers of files. I think it makes sense to add a parameter to store the `stdin` flag for the command being wrapped, so this command can run against files in either mode.

**Comment by hallettj** [comment]
Thank you for the feedback! Is slow performance an impediment to you using git-format-staged? It does sound like minimizing forking could be a good optimization. But IIUC it would only come up if you stage a lot of files at the same time. I'm hesitant to spend time on the change until I have a report of a problem in real-world use.

**Comment by hallettj** [comment]
I have noticed that git-format-staged can take a while on merge commits where changes to a lot of files sometimes accumulate in one commit. In those cases files are generally fully-staged. It could be useful to explore options to speed up such cases. Unfortunately I don't have the free time to work on that right now.
