### ISSUE TITLE
Docs: update references of `prettier` to remove `--stdin` mentions

### ISSUE THREAD

**Issue by rogerluan** [hallettj/git-format-staged#57]
Since https://github.com/prettier/prettier/pull/7668 the --stdin argument has been removed, so the documentation in this repo should reflect that (both in the README file as well as in the --help prompt)

**Comment by hallettj** [comment]
Thanks for pointing that out!

**Comment by rogerluan** [comment]
Thanks for the super fast turnaround @hallettj ! 🚀
