### ISSUE TITLE
Feature request: `--verbose` mode

### ISSUE THREAD

**Issue by rogerluan** [hallettj/git-format-staged#58]
I've been finding it hard to trace down why my integration is not working. If there was a --verbose mode, I'd have definitely enabled it in an effort to understand what's going on 😬

**Comment by hallettj** [comment]
This sounds like a good idea. I'll put it on my todo list.

**Comment by sdilts** [comment]
I don't feeling like going through the rigamarole of GitHub merge requests, so here's a patch that adds a basic version of the feature: the `--verbose` option prints out the format commands as they are executed. It was enough for me to figure out what was going wrong.

[0001-Add-verbose-option-to-git-format-staged.patch](https://github.com/hallettj/git-format-staged/files/11235282/0001-Add-verbose-option-to-git-format-staged.patch)

You can apply this patch using `git-am`: https://git-scm.com/docs/git-am
