### ISSUE TITLE
macOS 12.3 doesn't ship with python2, time to migrate to python3

### ISSUE THREAD

**Issue by alistra** [hallettj/git-format-staged#67]
The script runner of `git-format-staged` is using `env python` in its shebang which is used for Python 2.

Python 2 is no longer supported and there was a long time to migrate.

Please migrate to python 3 with the runner script :) 

PS I'm not asking for tips how to install `python2`

**Comment by victorBaro** [comment]
Any updates on this?

**Comment by hallettj** [comment]
No updates in the last two days, no. But there are few issues I've been meaning to work on in this project so I've set aside time this weekend for merging fixes, and pushing an updated release.

**Comment by alistra** [comment]
@hallettj probably just changing the `env python` to `env python3` would be sufficient and releasing, the comment claims it works under python 3

**Comment by hallettj** [comment]
Thank you for submitting the issue! I really appreciate the help to make sure that this program continues to work for everyone.
