### ISSUE TITLE
Warning: could not apply formatting changes to working tree file

### ISSUE THREAD

**Issue by raphaeloliveira** [hallettj/git-format-staged#8]
Hi @hallettj, thanks for the script. Its description talks about the exact issue my team is facing. We are trying to use your script alongside https://github.com/nicklockwood/SwiftFormat, to format our SwiftCode. There is even an open issue there https://github.com/nicklockwood/SwiftFormat/issues/223 talking about the problems with the proposed commit hook, that as we know, would not work on partially staged files.

Unfortunately, when I run `git-format-staged` with SwiftFormat, I keep getting
```
./scripts/git-format-staged.sh: warning: could not apply formatting changes to working tree file
```
and I don't fully understand why. Not sure if it's something related to how Swiftformat outputs the files?

I'm running the command 
`./scripts/git-format-staged.sh --formatter 'swiftformat --swiftversion 5.0 --config ".swiftformat" .' './*.swift'`

Output:
```
SwiftFormat completed in 0.68s.
1/743 files formatted, 6 files skipped.
./scripts/git-format-staged.sh: warning: could not apply formatting changes to working tree file MyProject/AppDelegate.swift
Reformatted MyProject/AppDelegate.swift with swiftformat --swiftversion 5.0 --config ".swiftformat" .
```

I also tried
`./scripts/git-format-staged.sh --formatter 'swiftformat --swiftversion 5.0 --config ".swiftformat" "{}"' './*.swift'` and got same result.

**Comment by raphaeloliveira** [comment]
Oh I think I finally found a solution, I had to use the `stdin` option from Swiftformat:

```
./scripts/git-format-staged.sh --formatter 'swiftformat --swiftversion 5.0 --config ".swiftformat" stdin' './*.swift'
```

⭐️

**Comment by raphaeloliveira** [comment]
Hey @hallettj, I'm experiencing another issue if I may:

I changed two consecutive lines but only staged the first one and committed. The resulting unstaged files have more than what I expected on the diff. It's basically trying to revert back the 1st line:

```bash
~/Workspace/iOS/MyProject (task/RemoveSwiftFormatBuildStep) $ git diff --cached
diff --git a/MyProject/AppDelegate.swift b/MyProject/AppDelegate.swift
index 5d9ef3db5..c1abcd69a 100644
--- a/MyProject/AppDelegate.swift
+++ b/MyProject/AppDelegate.swift
@@ -21,6 +21,7 @@ class AppDelegate: UIResponder, UIApplicationDelegate {
         window = UIWindow(frame: UIScreen.main.bounds)
         appController.onAppDidFinishLaunching(launchOptions: launchOptions)
         deeplinkManager.handleEnv()
+        let    a   =   10 // staging this line
         return true
     }
 
~/Workspace/iOS/MyProject (task/RemoveSwiftFormatBuildStep) $ git diff
diff --git a/MyProject/AppDelegate.swift b/MyProject/AppDelegate.swift
index c1abcd69a..8bf4eb53e 100644
--- a/MyProject/AppDelegate.swift
+++ b/MyProject/AppDelegate.swift
@@ -22,6 +22,7 @@ class AppDelegate: UIResponder, UIApplicationDelegate {
         appController.onAppDidFinishLaunching(launchOptions: launchOptions)
         deeplinkManager.handleEnv()
         let    a   =   10 // staging this line
+        let    b   =   11 // not staging this line
         return true
     }
 
~/Workspace/iOS/MyProject (task/RemoveSwiftFormatBuildStep) $ git commit -m "test"
Running SwiftFormat...
Swiftformat completed successfully.
./scripts/git-format-staged.sh: warning: could not apply formatting changes to working tree file MyProject/AppDelegate.swift
Reformatted MyProject/AppDelegate.swift with mint run --silent swiftformat swiftformat --swiftversion 5.0 --config ".swiftformat" stdin
[task/RemoveSwiftFormatBuildStep 80d85529c] test
 1 file changed, 1 insertion(+)
~/Workspace/iOS/MyProject (task/RemoveSwiftFormatBuildStep) $ git diff
diff --git a/MyProject/AppDelegate.swift b/MyProject/AppDelegate.swift
index ad8159171..8bf4eb53e 100644
--- a/MyProject/AppDelegate.swift
+++ b/MyProject/AppDelegate.swift
@@ -21,7 +21,8 @@ class AppDelegate: UIResponder, UIApplicationDelegate {
         window = UIWindow(frame: UIScreen.main.bounds)
         appController.onAppDidFinishLaunching(launchOptions: launchOptions)
         deeplinkManager.handleEnv()
-        let a = 10 // staging this line
+        let    a   =   10 // staging this line
+        let    b   =   11 // not staging this line
         return true
     }
 
```

Any ideas why?

**Comment by raphaeloliveira** [comment]
I think it might actually be related to https://github.com/hallettj/git-format-staged/pull/6. I tried with the changes @nc-holodakg suggested and it worked well. But yeah, I don't know how bad it is to apply patches with 0 context lines.

**Comment by hallettj** [comment]
I'm glad you're finding the project useful, and that you were able to resolve the first issue with the `stdin` option. Unfortunately the issue of the spurious unstaged change in the `let a` line cannot be avoided without setting the number of context lines to zero, and I'm not convinced that's safe.

When you stage changes there are two copies of the file: the staged version which is kept in a behind-the-scenes location in the git object database, and the working copy. Git-format-staged changes the staged copy, and attempts to merge formatting changes into the working copy. If a reformatted line is too close to an unstaged line the patch can't apply cleanly. (The exact distance is equal to the number of context lines in the patch - if the two lines are adjacent the patch will only apply with zero context.) In particular there can be ambiguity on which order lines from the two sides of the merge should appear in the merged result. My intention is to keep git-format-staged somewhat conservative about merging changes cleanly to avoid introducing incorrect changes to working files.

You're spot on that the working file "reverts" the formatting change to the `let a` line. But you'll notice that if you stage the reversion, either by itself or with other changes, the reversion will go away by itself when the formatter runs again on pre-commit. Alternatively the reversion should go away if you run swiftformat manually, or via editor integration.

**Comment by raphaeloliveira** [comment]
Hi @hallettj, thank you for your reply. By any chance do you have an example of what would be a bad merge if we give 0 lines of context? Trying to understand if this is a likely scenario when formatting code. 

As an alternative, I wouldn't actually mind having the unstaged files also formatted, in that case, there wouldn't be conflicts, right? What do you think?
