### ISSUE TITLE
"Invalid escape sequence" errors when run with python 3.12.0

### ISSUE THREAD

**Issue by brzzdev** [hallettj/git-format-staged#89]
`invalid escape sequence '\{'` for `file_path_placeholder = re.compile('\{\}')`

`invalid escape sequence '\d'` for `diff_pat = re.compile('^:(\d+) (\d+) ([a-f0-9]+) ([a-f0-9]+) ([A-Z])(\d+)?\t([^\t]+)(?:\t([^\t]+))?$')`

**Comment by herrernst** [comment]
me too. works with python 3.11.

**Comment by hallettj** [comment]
Thanks for the reports! I've reproduced the error, and I'll work on a fix.
